# This is a basic workflow to help you get started with Actions

name: Build Linux

# Controls when the action will run.
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  # schedule:
  #   - cron: "0 0 * * */3"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

env:
  TZ: Asia/Shanghai

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildx:
    runs-on: ${{ matrix.target.os }}
    strategy:
      matrix:
        target:
          - { os: macos-12, arch: x86_64, suffix: darwin }
          - { os: self-hosted, arch: arm64, suffix: linux }
          - { os: ubuntu-22.04, arch: amd64, suffix: linux }
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d')"
      -
        name: Installing Graalvm dependencies
        run: sudo apt install -y make gcc libz-dev
        if:  matrix.target.suffix  == 'linux'
      -
        name: Setup Graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'
      - run: chmod +x ./gradlew
      # Set VERSION_INFORMATION
      - run: echo "VERSION_INFORMATION=$(${{github.workspace}}/gradlew --no-daemon -q ciPrintVersionInformation)" >> $GITHUB_ENV
      -
        name: Build project
        run: ./gradlew --no-daemon nativeCompile
      -
        run: mv build/native/nativeCompile/aliyundrive-webdav build/native/nativeCompile/aliyundrive-webdav-${{matrix.target.suffix}}-${{matrix.target.arch}}
      -
        name: Archive artifacts
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'tar'
          filename: 'aliyundrive-webdav-${{matrix.target.suffix}}-${{matrix.target.arch}}.tar.gz'
          directory: 'build/native/nativeCompile/'
          path: "./aliyundrive-webdav-${{matrix.target.suffix}}-${{matrix.target.arch}}"
      -
        name: Upload artifacts
        uses: bxb100/action-upload-webdav@v1
        with:
          webdav_address: ${{secrets.WEBDAV_ADDRESS}}
          webdav_username: ${{secrets.WEBDAV_USERNAME}}
          webdav_password: ${{secrets.WEBDAV_PASSWORD}}
          webdav_upload_path: "/${{ env.VERSION_INFORMATION }}"
          files: |
            build/native/nativeCompile/aliyundrive-webdav-${{matrix.target.suffix}}-${{matrix.target.arch}}.tar.gz
